### ISSUE TITLE
Got a SIGSEGV while executing native code.

### ISSUE THREAD

**Issue by kamild1996** [DeathCradle/Terraria-s-Dedicated-Server-Mod#146]
the server was idle with no players, then i don't even know when this error appeared
http://pastebin.com/hVN71CN2

i remember the same error appearing when running minecraft server which was fixed by underclocking my memory. after that the minecraft server was running for like 2 weeks constantly without an error but terraria server crashed way sooner

**Comment by DeathCradle** [comment]
Try disabling upnp, seems there is something going on with that

**Comment by D1G1T4L3CH0** [comment]
I had those errors until I freed some ram on my server. Haven't had them since.

**Comment by kamild1996** [comment]
I have about 3.5 GB of free RAM available so I do not think that's the issue.
Also thanks for the quick response, I'll try disabling UPnP and I'll let you know.

**Comment by D1G1T4L3CH0** [comment]
That is the correct command line. It should be working. Check to make sure you have a world specified in the config and also that it exists unless you use the autocreate option.

**Comment by kamild1996** [comment]
Autocreate option is enabled. In server.config I've defined all those parameters like server/RCON ports but I'm still being asked to choose the port and the world to load.
Maybe there's another way to define parameters?

**Comment by D1G1T4L3CH0** [comment]
You can define them on the command line if you like. http://terraria.gamepedia.com/Server#Command_line_parameters But there seems to be a problem with your config maybe. But this is off topic. Please open a new issue for this one if you continue to have issues. I think you should post your config file if you do, there may be some error in it.

**Comment by kamild1996** [comment]
I'll try this and if I still experience any issues, I'll open a new issue.
This one can be closed anyway - after disabling UPnP the server has been running without crashes, so it's solved :)

**Comment by D1G1T4L3CH0** [comment]
Great! :smile:
